### ISSUE TITLE
Urgent Fixes- Coins get deleted after a day 

### ISSUE THREAD

**Issue by Francaolisa** [Francaolisa/Coinrate#4]
**Issue 1:** 

Coins listed in today tab gets deleted after 24hrs, 
It's meant to be moved automatically to the **all coins** tab after 7days. Pls, fix it.

Issue 2:

When I add a coin to the **presale table**, it shows ended

Issue 3:

Description field should be RichText which allows text, image, links, bold text, font size, alignment etc.

issue 4:

Remove required from rate and rated column. **Exchange field** should accept multiple slink and text. I should be able to add an exchange name and embed the link on that text as shown in the sample site.

Issue 5:

Copy contract address does not tell the user that the address has been copied. Pls fix

Issue 6:

Add marketcap for each coin.

Pls let's fix all as fast as possible to move to the next task.

**Comment by chinmoykalita** [comment]
Have been fixed.
